### ISSUE TITLE
The library is broken now, probably some changed on the stark side

### ISSUE THREAD

**Issue by cpcs** [junta/dydx-v3-rust#9]
If run the tests, we'll get

400 Bad Request", message: "{\"errors\":[{\"msg\":\"Invalid signature for ApiKey request

**Comment by junta** [comment]
This is a known error on dYdX testnet now.
waiting for dYdX core team solves this issue.

**Comment by junta** [comment]
dYdX testnet is migrated from Ropsten to Goerli, so updated NETWORK_ID in test codes with this commit
https://github.com/junta/dydx-v3-rust/commit/5d5c394572e1e699e966aa8cdb0f2b1c03a0d758

thank you for raising this issue!
